### ISSUE TITLE
Add doxygen style documentation

### ISSUE THREAD

**Issue by L3nn0x** [RavenX8/osIROSE-new#20]
We need to add documentation doxygen-like for at least Core and RoseCommon so people can get involved more easily and don't have to crawl through pages of code to find the right function/class/member or so they don't re-create functions that are already in the code base.

**Comment by RavenX8** [comment]
I thought about this but every time I've tried doing something like this, I had forgotten about it until it was so out dated. Also I don't like adding the documentation to the source code directly so it would need to be in an external file ref the code.

Also we have a wiki on github that we should think about filling out. https://github.com/RavenX8/osIROSE-new/wiki

**Comment by L3nn0x** [comment]
I actually don't know what to put into the wiki...
If it were me I'd put there the documentation from doxygen.
