### ISSUE TITLE
Rose Packet types should be in their own file

### ISSUE THREAD

**Issue by RavenX8** [RavenX8/osIROSE-new#9]
In CPacket we currently have rose packet structures and enums defined. We should move that out into the rosecommon project and make a child class named CRosePacket.

**Comment by L3nn0x** [comment]
There is already a CRosePacket struct in the rosecommon project

**Comment by L3nn0x** [comment]
I merged the Cpacket struct into the CRosePacket one, and made sure CRosePacket was used everywhere instead of CPacket.

**Comment by L3nn0x** [comment]
@RavenX8 : are the changes enough ?

**Comment by RavenX8** [comment]
1b98fcf10f0d1997d2d2933a362c4b24cb73b701 - Corrected the test files to use CRosePacket
36b9d1ab838458644d0402edbe2089ffada49c2b - Adapted existing code to use CRosePacket instead of CPacket
042495478b60fa70ffd22635a1cd65b504293b08 - Merged the CPacket class into CRosePacket

**Comment by RavenX8** [comment]
They look good.
